version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      java-test-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.mockito:*"
      maven-build-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.owasp:dependency-check-maven"
          - "org.sonatype.central:central-publishing-maven-plugin"
          - "me.fabriciorby:maven-surefire-junit5-tree-reporter"
          - "org.codehaus.mojo:exec-maven-plugin"
          - "io.github.coffeelibs:jextract-maven-plugin"
      java-production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "org.junit.jupiter:*"
          - "org.mockito:*"
          - "org.apache.maven.plugins:*"
          - "org.owasp:dependency-check-maven"
          - "org.sonatype.central:central-publishing-maven-plugin"
          - "me.fabriciorby:maven-surefire-junit5-tree-reporter"
          - "org.codehaus.mojo:exec-maven-plugin"
          - "io.github.coffeelibs:jextract-maven-plugin"
  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
