commit_message: '[ci skip]'
files:
  - source: /src/main/resources/WinIntegrationsBundle.properties
    translation: /src/main/resources/WinIntegrationsBundle_%two_letters_code%.properties
    escape_quotes: 0
    escape_special_characters: 0
