/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_autostart_WinShortcutCreation_Native */

#ifndef _Included_org_cryptomator_windows_autostart_WinShortcutCreation_Native
#define _Included_org_cryptomator_windows_autostart_WinShortcutCreation_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_autostart_WinShortcutCreation_Native
 * Method:    createShortcut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_autostart_WinShortcutCreation_00024Native_createShortcut
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
