/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_keychain_WinDataProtection_Native */

#ifndef _Included_org_cryptomator_windows_keychain_WinDataProtection_Native
#define _Included_org_cryptomator_windows_keychain_WinDataProtection_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_keychain_WinDataProtection_Native
 * Method:    protect
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WinDataProtection_00024Native_protect
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_cryptomator_windows_keychain_WinDataProtection_Native
 * Method:    unprotect
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WinDataProtection_00024Native_unprotect
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
