/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_autostart_WinShellLinks_Native */

#ifndef _Included_org_cryptomator_windows_autostart_WinShellLinks_Native
#define _Included_org_cryptomator_windows_autostart_WinShellLinks_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_autostart_WinShellLinks_Native
 * Method:    createShortcut
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_autostart_WinShellLinks_00024Native_createShortcut
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_cryptomator_windows_autostart_WinShellLinks_Native
 * Method:    createAndGetStartupFolderPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_windows_autostart_WinShellLinks_00024Native_createAndGetStartupFolderPath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
