/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_keychain_WinHello_Native */

#ifndef _Included_org_cryptomator_windows_keychain_WinHello_Native
#define _Included_org_cryptomator_windows_keychain_WinHello_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_keychain_WinHello_Native
 * Method:    setEncryptionKey
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WinHello_00024Native_setEncryptionKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_cryptomator_windows_keychain_WinHello_Native
 * Method:    getEncryptionKey
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WinHello_00024Native_getEncryptionKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
