/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_revealpaths_ShellRevealPathsService_Native */

#ifndef _Included_org_cryptomator_windows_revealpaths_ShellRevealPathsService_Native
#define _Included_org_cryptomator_windows_revealpaths_ShellRevealPathsService_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_revealpaths_ShellRevealPathsService_Native
 * Method:    reveal
 * Signature: ([B[[B)I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_revealpaths_ShellRevealPathsService_00024Native_reveal
  (JNIEnv *, jobject, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
