/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_keychain_WindowsHello_Native */

#ifndef _Included_org_cryptomator_windows_keychain_WindowsHello_Native
#define _Included_org_cryptomator_windows_keychain_WindowsHello_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_keychain_WindowsHello_Native
 * Method:    isSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_windows_keychain_WindowsHello_00024Native_isSupported
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_keychain_WindowsHello_Native
 * Method:    encrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WindowsHello_00024Native_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_cryptomator_windows_keychain_WindowsHello_Native
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_windows_keychain_WindowsHello_00024Native_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
