/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_uiappearance_WinAppearance_Native */

#ifndef _Included_org_cryptomator_windows_uiappearance_WinAppearance_Native
#define _Included_org_cryptomator_windows_uiappearance_WinAppearance_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    getCurrentTheme
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_getCurrentTheme
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    setToLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_setToLight
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    setToDark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_setToDark
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    prepareObserving
 * Signature: (Lorg/cryptomator/windows/uiappearance/WinAppearanceListener;)I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_prepareObserving
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    observe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_observe
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    stopObserving
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_stopObserving
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    callBackToJava
 * Signature: (Lorg/cryptomator/windows/uiappearance/WinAppearance;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_callBackToJava
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
