/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_uiappearance_WinAppearance_Native */

#ifndef _Included_org_cryptomator_windows_uiappearance_WinAppearance_Native
#define _Included_org_cryptomator_windows_uiappearance_WinAppearance_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    getCurrentTheme
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_getCurrentTheme
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    setToLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_setToLight
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    setToDark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_setToDark
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_windows_uiappearance_WinAppearance_Native
 * Method:    waitForNextThemeChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_windows_uiappearance_WinAppearance_00024Native_waitForNextThemeChange
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
