/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_windows_notify_WinToasts_Native */

#ifndef _Included_org_cryptomator_windows_notify_WinToasts_Native
#define _Included_org_cryptomator_windows_notify_WinToasts_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_windows_notify_WinToasts_Native
 * Method:    sendToastNotification
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_org_cryptomator_windows_notify_WinToasts_00024Native_sendToastNotification
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
