name: Build
on:
  [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Ensure to use tagged version
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: mvn versions:set --file ./pom.xml -DnewVersion=${GITHUB_REF##*/}
      - name: Build and Test
        id: buildAndTest
        run: mvn -B clean test -Pdependency-check
      - name: Codesign DLL
        uses: skymatic/code-sign-action@v2
        with:
          certificate: ${{ secrets.WIN_CODESIGN_P12_BASE64 }}
          password: ${{ secrets.WIN_CODESIGN_P12_PW }}
          certificatesha1: 5FC94CE149E5B511E621F53A060AC67CBD446B3A
          timestampUrl: 'http://timestamp.digicert.com'
          folder: ./src/main/resources
      - name: Package and Install
        id: packAndInstall
        run: mvn -B install -DskipNativeCompile
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: target/*.jar
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref }}
          prerelease: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          generate_release_notes: true