name: Publish to GitHub Packages
on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') # only allow publishing tagged versions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'maven'
      - name: Enforce project version ${{ github.event.release.tag_name }}
        run: mvn versions:set -B -DnewVersion="${{ github.event.release.tag_name }}"
      - name: Deploy
        run: mvn deploy -B -DskipTests -Psign,deploy-github --no-transfer-progress -DdevCommandFileDir="${{ vars.MSVC_DEV_FILES_DIR }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          MAVEN_GPG_KEY_FINGERPRINT: ${{ vars.RELEASES_GPG_KEY_FINGERPRINT }}